name: QA CI/CD
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ember
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: global add ember-cli
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build module
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: delete from s3
        run: aws s3 rm s3://qa.porter.family --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: sync
        run: aws s3 sync --acl public-read ./dist s3://qa.porter.family
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id E3CDMFD7X9EJ0M --paths /*
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2